# Generated by Django 3.0.6 on 2023-03-19 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('i_im_id', models.CharField(max_length=8, unique=True)),
                ('i_name', models.CharField(max_length=50)),
                ('i_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('w_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('w_name', models.CharField(max_length=50)),
                ('w_street', models.CharField(max_length=50)),
                ('w_city', models.CharField(max_length=50)),
                ('w_country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_qty', models.IntegerField()),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpcc.Item')),
                ('w_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpcc.Warehouses')),
            ],
        ),
    ]
