# Generated by Django 3.0.6 on 2023-03-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpcc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Items',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='id',
        ),
        migrations.AddField(
            model_name='stocks',
            name='s_id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
